---
---
---
apiVersion: v1
kind: Service
metadata:
  name: postgres          # must match StatefulSet.spec.serviceName
  namespace: kafka
  labels:
    app: postgres
spec:
  clusterIP: None         # headless
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  namespace: kafka
  labels:
    app: postgres
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport # separate client-facing service
  namespace: kafka
  labels:
    app: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 30032     # optional; remove to auto-assign
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: kafka
  labels:
    app: postgres
spec:
  serviceName: "postgres-hl"   # must reference the HEADLESS service
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
            - name: TZ
              value: "Asia/Ho_Chi_Minh"
            - name: POSTGRES_INITDB_ARGS
              value: "--timezone=Asia/Ho_Chi_Minh"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
        labels:
          app: postgres
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 3Gi
